FROM microsoft/dotnet:2.1-sdk AS build-env
WORKDIR /app

COPY . .
RUN dotnet restore ./TaskManagement.Api/

# Copy everything else and build
WORKDIR /app/TaskManagement.Api/
RUN dotnet publish -c Release -o out

# Build runtime image
FROM microsoft/dotnet:2.1-aspnetcore-runtime
WORKDIR /app
COPY --from=build-env /app/TaskManagement.Api/out .
ENTRYPOINT ["dotnet", "TaskManagement.Api.dll"]